version: '3.8'

services:
  web:
    build: .
    command: gunicorn elanel_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - certbot_conf:/etc/letsencrypt/:rw

    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./deploy/nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - certbot_conf:/etc/letsencrypt/:rw
      - certbot_data:/var/www/certbot/:rw
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_conf:/etc/letsencrypt/:rw
      - certbot_data:/var/www/certbot/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email lautaro.rodriguez553@gmail.com -d elanelsys.com --agree-tos 
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_conf:
  certbot_data:
 
 
