# Generated by Django 4.0.6 on 2022-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_electrodomestico_cuotas_remove_moto_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='ficha_tecnica',
            field=models.FileField(blank=True, default=None, null=True, upload_to='f_tecnicas/electrodomesticos/'),
        ),
        migrations.AddField(
            model_name='moto',
            name='ficha_tecnica',
            field=models.FileField(blank=True, default=None, null=True, upload_to='f_tecnicas/motos/'),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='imagen_portada',
            field=models.ImageField(default=None, upload_to='images/electrodomesticos/'),
        ),
    ]
