# Generated by Django 4.0.6 on 2022-12-28 15:47

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_electrodomestico_usado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodomestico',
            name='descripcion',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='moto',
            name='descripcion',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='soluciondineraria',
            name='descripcion',
            field=django_quill.fields.QuillField(),
        ),
    ]
