# Generated by Django 4.0.6 on 2022-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_electrodomestico_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='servicio',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Premium', 'Premium')], default='Basico', max_length=50),
        ),
        migrations.AddField(
            model_name='moto',
            name='servicio',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Premium', 'Premium')], default='Basico', max_length=50),
        ),
    ]
