# Generated by Django 4.0.6 on 2022-12-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_electrodomestico_monto_servicio_por_couta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioparacliente',
            name='monto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beneficioparacliente',
            name='producto',
            field=models.CharField(default='', max_length=80),
        ),
    ]
