# Generated by Django 4.0.6 on 2023-03-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_remove_soluciondineraria_monto_cuota'),
        ('market', '0022_alter_personal_nombre_completo_and_more'),
    ]

    operations = [
    ]
