# Generated by Django 4.0.6 on 2022-07-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_de_categoria', models.CharField(choices=[('motos', 'Motos'), ('soluciones_dinerarias', 'Soluciones dinerarias'), ('electrodomesticos', 'Electrodomesticos'), ('usados', 'Usados'), ('beneficios_para_clientes', 'Beneficios para clientes')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('url_instagram', models.URLField(blank=True, max_length=255)),
                ('url_facebook', models.URLField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('especificaciones', models.TextField()),
                ('forma_de_pago', models.CharField(max_length=255)),
                ('usado', models.BooleanField()),
                ('cuotas', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SolucionDineraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuotas', models.IntegerField(max_length=3)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('provincia', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('objetivo', models.CharField(max_length=254)),
                ('num_telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
