# Generated by Django 4.0.6 on 2022-12-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioParaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_completo', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('servicio', models.CharField(max_length=254)),
                ('num_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=120)),
                ('dni', models.CharField(max_length=8)),
                ('provincia', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('objetivo', models.CharField(max_length=254)),
                ('num_telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('combo', models.CharField(choices=[('cocina', 'cocina'), ('gamer', 'gamer'), ('musica', 'musica'), ('tv', 'tv')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('forma_de_pago', models.CharField(max_length=255)),
                ('imagen_portada', models.ImageField(default=None, upload_to='images/motos/')),
                ('usado', models.BooleanField()),
                ('cuotas', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('kilometros', models.IntegerField(blank=True, default='')),
                ('año', models.IntegerField(blank=True, default=0)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('forma_de_pago', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_portada', models.ImageField(default=None, upload_to='images/motos/')),
                ('usado', models.BooleanField()),
                ('cuotas', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('num_telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(default=None, upload_to='archivos/cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('imagen_portada', models.ImageField(default=None, upload_to='images/posts')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionDineraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuotas', models.PositiveSmallIntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default=None, upload_to='images/posts')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.post')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/motos/')),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.moto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenElectrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/electrodomesticos/')),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.electrodomestico')),
            ],
        ),
    ]
