# Generated by Django 4.0.6 on 2022-09-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioParaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia_titulo', models.CharField(choices=[('tecnica_para_electrodomesticos', 'Técnica para Electromesticos'), ('mecanica_de_motos', 'Mecánica de Motos')], max_length=50)),
                ('nombre_tecnico', models.CharField(default='', max_length=50)),
                ('num_contacto', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=120)),
                ('dni', models.CharField(max_length=8)),
                ('provincia', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('objetivo', models.CharField(max_length=254)),
                ('num_telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('num_telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ImageField(default=None, upload_to='archivos/cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('imagen_portada', models.ImageField(default=None, upload_to='images/posts')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionDineraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuotas', models.PositiveSmallIntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('titulo_de_categoria', models.CharField(choices=[('motos', 'Motos'), ('soluciones_dinerarias', 'Soluciones dinerarias'), ('electrodomesticos', 'Electrodomesticos'), ('usados', 'Usados'), ('beneficios_para_clientes', 'Beneficios para clientes')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('url_instagram', models.URLField(blank=True, max_length=255)),
                ('url_facebook', models.URLField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('especificaciones', models.TextField()),
                ('forma_de_pago', models.CharField(max_length=255)),
                ('imagen_portada', models.ImageField(default=None, upload_to='images/productos/')),
                ('usado', models.BooleanField()),
                ('cuotas', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('nombre', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PostImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default=None, upload_to='images/posts')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.post')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/productos/')),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.producto')),
            ],
        ),
    ]
