# Generated by Django 4.0.6 on 2022-07-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(default=None, upload_to='images/posts'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_portada',
            field=models.ImageField(default=None, upload_to='images/productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cuotas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='soluciondineraria',
            name='cuotas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='PostImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default=None, upload_to='images/posts')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.post')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default=None, upload_to='images/productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='market.producto')),
            ],
        ),
    ]
