# Generated by Django 4.0.6 on 2022-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cv',
            field=models.FileField(default=None, upload_to='archivos/cv/'),
        ),
    ]
