# Generated by Django 4.0.6 on 2022-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='año',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='moto',
            name='forma_de_pago',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
