# Generated by Django 4.0.6 on 2022-07-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_post_imagen_portada_producto_imagen_portada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioParaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia_titulo', models.CharField(choices=[('tecnica_para_electrodomesticos', 'Técnica para Electromesticos'), ('mecanica_de_motos', 'Mecánica de Motos')], max_length=50)),
            ],
        ),
    ]
