# Generated by Django 4.0.6 on 2022-12-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_moto_año_alter_moto_forma_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='año',
            field=models.IntegerField(blank=True),
        ),
    ]
