# Generated by Django 4.0.6 on 2022-09-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_beneficioparacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='beneficioparacliente',
            name='nombre_tecnico',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficioparacliente',
            name='num_contacto',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default='', max_length=120),
        ),
    ]
