# Generated by Django 4.0.6 on 2022-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_moto_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cuotas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='forma_de_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='kilometros',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
