# Generated by Django 4.0.6 on 2022-12-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_numadjudicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrodomestico',
            name='cuotas',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='cuotas',
        ),
        migrations.RemoveField(
            model_name='soluciondineraria',
            name='cuotas',
        ),
        migrations.AddField(
            model_name='electrodomestico',
            name='cuota',
            field=models.CharField(choices=[('24', '24'), ('30', '30'), ('48', '48'), ('60', '60')], default='24', max_length=2),
        ),
        migrations.AddField(
            model_name='moto',
            name='cuota',
            field=models.CharField(choices=[('24', '24'), ('30', '30'), ('48', '48'), ('60', '60')], default='24', max_length=2),
        ),
        migrations.AddField(
            model_name='soluciondineraria',
            name='cuota',
            field=models.CharField(choices=[('24', '24'), ('30', '30'), ('48', '48'), ('60', '60')], default='24', max_length=2),
        ),
    ]
