# Generated by Django 4.0.6 on 2022-12-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_cliente_dni_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrodomestico',
            name='usado',
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='forma_de_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
