# Generated by Django 4.0.6 on 2022-12-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_electrodomestico_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha_limite',
        ),
    ]
