# Generated by Django 4.0.6 on 2022-12-28 21:40

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_post_fecha_remove_post_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodomestico',
            name='descripcion',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='descripcion',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soluciondineraria',
            name='descripcion',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
