# Generated by Django 4.0.6 on 2022-12-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_electrodomestico_servicio_moto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodomestico',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Premium', 'Premium')], default='Basico', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='servicio',
            field=models.CharField(blank=True, choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Premium', 'Premium')], default='Basico', max_length=50, null=True),
        ),
    ]
