# Generated by Django 4.0.6 on 2022-12-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_electrodomestico_servicio_alter_moto_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='monto_servicio_por_couta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='monto_servicio_por_couta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
