# Generated by Django 4.1 on 2023-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_beneficioparacliente_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tamaño',
            field=models.CharField(choices=[('Celular', 'Celular'), ('Computadoras', 'Computadoras')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numadjudicado',
            name='año',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
