# Generated by Django 4.1 on 2023-02-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_post_tamaño_alter_numadjudicado_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
