# Generated by Django 4.0.6 on 2023-02-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_rename_tamaño_post_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soluciondineraria',
            name='monto_cuota',
        ),
    ]
