# Generated by Django 4.0.6 on 2023-03-02 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alter_cliente_num_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioparacliente',
            name='monto',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
        migrations.AlterField(
            model_name='beneficioparacliente',
            name='nombre_completo',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='beneficioparacliente',
            name='num_telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default='', max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre_completo',
            field=models.CharField(default='', max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='num_telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
    ]
