# Generated by Django 4.0.6 on 2023-03-02 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_alter_beneficioparacliente_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioparacliente',
            name='monto',
            field=models.FloatField(validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
        migrations.AlterField(
            model_name='beneficioparacliente',
            name='nombre_completo',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default='', max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')]),
        ),
    ]
