# Generated by Django 4.0.6 on 2023-03-02 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_beneficioparacliente_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='nombre_completo',
            field=models.CharField(default='', max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ ]+$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='num_telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Ingrese un número válido')]),
        ),
    ]
