# Generated by Django 4.0.6 on 2023-12-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_merge_20230320_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soluciondineraria',
            name='cuota',
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='combo',
            field=models.CharField(choices=[('cocina', 'cocina'), ('tecnologia', 'tecnologia'), ('dormitorio', 'dormitorio'), ('living', 'living'), ('hogar', 'hogar')], max_length=100),
        ),
    ]
