# Generated by Django 4.0.6 on 2024-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_remove_soluciondineraria_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numadjudicado',
            name='año',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
