# Generated by Django 4.0.6 on 2024-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_alter_numadjudicado_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen_portada',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='postImage_celular',
            field=models.ImageField(default=None, upload_to='images/posts', verbose_name='Post de celular'),
        ),
        migrations.AddField(
            model_name='post',
            name='postImage_computadora',
            field=models.ImageField(default=None, upload_to='images/posts', verbose_name='Post de computadora'),
        ),
        migrations.DeleteModel(
            name='PostImagenes',
        ),
    ]
