# Generated by Django 4.0.6 on 2024-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_remove_post_descripcion_remove_post_imagen_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage_celular',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/posts', verbose_name='Post de celular'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage_computadora',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/posts', verbose_name='Post de computadora'),
        ),
    ]
